version: '3.6'

networks:
  ngimgproxy:

services:
  nginx:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - ngimgproxy
  imgproxy:
    image: darthsim/imgproxy:v2.16.3
    restart: always
    environment:
      IMGPROXY_KEY: "${IMGPROXY_KEY}"
      IMGPROXY_SALT: "${IMGPROXY_SALT}"
      IMGPROXY_SIGNATURE_SIZE: 32
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 60
      IMGPROXY_TTL: 31536000
      IMGPROXY_CONCURRENCY: 2
      IMGPROXY_MAX_SRC_RESOLUTION: 8
      IMGPROXY_MAX_SRC_FILE_SIZE: 2097152
      IMGPROXY_QUALITY: 90
      IMGPROXY_JPEG_PROGRESSIVE: 'false'
      IMGPROXY_ENABLE_WEBP_DETECTION: 'false'
      IMGPROXY_ENFORCE_WEBP: 'false'
      IMGPROXY_MAX_ANIMATION_FRAMES: 50
      IMGPROXY_WRITE_TIMEOUT: 5
      IMGPROXY_LOG_LEVEL: warn
      IMGPROXY_PROMETHEUS_BIND: "0.0.0.0:8081"
    networks:
      - ngimgproxy
